version: "3"
services:
  master:
    container_name: master
    image: jenkins/jenkins:lts #ここがレポ名が変わってる
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    links:
      - slave01
  slave01:
    container_name: slave01
    image: jenkins/ssh-agent:latest-jdk11 #ここもかわってる
    environment: #環境変数名もかわってる
      - JENKINS_AGENT_SSH_PUBKEY=xxx
